# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWorkspace < Formula
  desc "A lightweight CLI tool for discovering, organizing, and navigating git repositories"
  homepage "https://github.com/daileyo/gws"
  version "2.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daileyo/gws/releases/download/v2.13.0/git-workspace_2.13.0_darwin_amd64.tar.gz"
      sha256 "60e0f1fa8e461e1e7757704294ebdd1dd5874fd412950f9b04a62096da62177c"

      define_method(:install) do
        bin.install "git-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daileyo/gws/releases/download/v2.13.0/git-workspace_2.13.0_darwin_arm64.tar.gz"
      sha256 "dc652fee6bf15fb57bb39fccb32a55019bfde4216faeede9e2ff3064a966c0a0"

      define_method(:install) do
        bin.install "git-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/gws/releases/download/v2.13.0/git-workspace_2.13.0_linux_amd64.tar.gz"
      sha256 "40d6064a994d08996fc8cf142602114827598f21123bc42ba385233c3aa20184"
      define_method(:install) do
        bin.install "git-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/gws/releases/download/v2.13.0/git-workspace_2.13.0_linux_arm64.tar.gz"
      sha256 "6d45c4355779a2a501f84c67104d0787bd6a47140ea2ef998d91c203474670c9"
      define_method(:install) do
        bin.install "git-workspace"
      end
    end
  end
end
