# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gws < Formula
  desc "A lightweight CLI tool for discovering, organizing, and navigating git repositories"
  homepage "https://github.com/daileyo/gws"
  version "2.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daileyo/gws/releases/download/v2.11.0/git-workspace_2.11.0_darwin_amd64.tar.gz"
      sha256 "e9b2b07914eee4ec89816a718991ab383e2340c0cb1399ab26d5550a29788723"

      define_method(:install) do
        bin.install "git-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daileyo/gws/releases/download/v2.11.0/git-workspace_2.11.0_darwin_arm64.tar.gz"
      sha256 "c61bef2f36d7fa9786f8b3d29b2046e0aedcac0faf29aa1502d3020bd0cf171c"

      define_method(:install) do
        bin.install "git-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/gws/releases/download/v2.11.0/git-workspace_2.11.0_linux_amd64.tar.gz"
      sha256 "5cfaae7246dc825c50cc83600414902e719ce6cc8a37832f6ab1785062eaae84"
      define_method(:install) do
        bin.install "git-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/gws/releases/download/v2.11.0/git-workspace_2.11.0_linux_arm64.tar.gz"
      sha256 "a49613949a0b54464a13b5458d4cfc47c9f3c57f9b903fa4d115b6f5c63f3eef"
      define_method(:install) do
        bin.install "git-workspace"
      end
    end
  end
end
