# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gws < Formula
  desc "A lightweight CLI tool for discovering, organizing, and navigating git repositories"
  homepage "https://github.com/daileyo/gws"
  version "2.11.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/daileyo/gws/releases/download/v2.11.1/git-workspace_2.11.1_darwin_amd64.tar.gz"
      sha256 "19cea47b8fa132bc7296f0f9cb33e6aeca4fe1838aee05982c3f0438a643a2d6"

      define_method(:install) do
        bin.install "git-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/daileyo/gws/releases/download/v2.11.1/git-workspace_2.11.1_darwin_arm64.tar.gz"
      sha256 "78f201ccf95b6df69acb8b0d2e5a88479023f5de6492e1a1f8ea666d3b6f075b"

      define_method(:install) do
        bin.install "git-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/gws/releases/download/v2.11.1/git-workspace_2.11.1_linux_amd64.tar.gz"
      sha256 "a0b59df254247e743240a047d8ed24509a73926210593068dc7e7e49b48e9f49"
      define_method(:install) do
        bin.install "git-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/daileyo/gws/releases/download/v2.11.1/git-workspace_2.11.1_linux_arm64.tar.gz"
      sha256 "bc77bbaa182e45324ce4f3ff71d44226759d66a7d3c9a96a5afaeaa386dcc668"
      define_method(:install) do
        bin.install "git-workspace"
      end
    end
  end
end
